/**
 * Skills catalog with Simple Icons slugs for the dashboard dropdown.
 * Format: { label: string; slug: string } - slug is used for cdn.simpleicons.org
 */
export const SKILLS_CATALOG: { group: string; skills: { label: string; slug: string }[] }[] = [
  {
    group: "Frontend / UI — Frameworks",
    skills: [
      { label: "Next.js", slug: "nextdotjs" },
      { label: "React", slug: "react" },
      { label: "Vue.js", slug: "vuedotjs" },
      { label: "Svelte", slug: "svelte" },
      { label: "Angular", slug: "angular" },
      { label: "Remix", slug: "remix" },
      { label: "Astro", slug: "astro" },
      { label: "Solid.js", slug: "solid" },
      { label: "Nuxt", slug: "nuxt" },
      { label: "Qwik", slug: "qwik" },
      { label: "Ember.js", slug: "emberdotjs" },
      { label: "Preact", slug: "preact" },
      { label: "Lit", slug: "lit" },
      { label: "Alpine.js", slug: "alpinedotjs" },
      { label: "Meteor", slug: "meteor" },
      { label: "Quasar", slug: "quasar" },
      { label: "Ionic", slug: "ionic" },
    ],
  },
  {
    group: "Frontend — Build Tools / Bundlers",
    skills: [
      { label: "Vite", slug: "vite" },
      { label: "Webpack", slug: "webpack" },
      { label: "Parcel", slug: "parcel" },
      { label: "Rollup", slug: "rollupdotjs" },
      { label: "esbuild", slug: "esbuild" },
      { label: "Turbopack", slug: "turbopack" },
      { label: "Nx", slug: "nx" },
      { label: "Turborepo", slug: "turborepo" },
      { label: "Snowpack", slug: "snowpack" },
      { label: "Babel", slug: "babel" },
      { label: "SWC", slug: "swc" },
    ],
  },
  {
    group: "Frontend — Styling / CSS",
    skills: [
      { label: "Tailwind CSS", slug: "tailwindcss" },
      { label: "Bootstrap", slug: "bootstrap" },
      { label: "Material-UI", slug: "mui" },
      { label: "Chakra UI", slug: "chakraui" },
      { label: "Ant Design", slug: "antdesign" },
      { label: "Emotion", slug: "emotion" },
      { label: "Styled Components", slug: "styledcomponents" },
      { label: "Bulma", slug: "bulma" },
      { label: "Stylus", slug: "stylus" },
      { label: "PostCSS", slug: "postcss" },
      { label: "UnoCSS", slug: "unocss" },
      { label: "Tailwind Typography", slug: "tailwindcss" },
      { label: "Radix UI", slug: "radixui" },
      { label: "Headless UI", slug: "headlessui" },
      { label: "Tailwind UI", slug: "tailwindcss" },
      { label: "DaisyUI", slug: "daisyui" },
      { label: "Flowbite", slug: "tailwindcss" },
    ],
  },
  {
    group: "Frontend — Languages",
    skills: [
      { label: "JavaScript", slug: "javascript" },
      { label: "TypeScript", slug: "typescript" },
      { label: "HTML5", slug: "html5" },
      { label: "CSS3", slug: "css3" },
      { label: "Sass", slug: "sass" },
      { label: "Less", slug: "less" },
      { label: "Pug", slug: "pug" },
    ],
  },
  {
    group: "Frontend — Animations / Graphics",
    skills: [
      { label: "Framer Motion", slug: "framer" },
      { label: "GSAP", slug: "greensock" },
      { label: "Three.js", slug: "threedotjs" },
      { label: "Lottie", slug: "lottie" },
      { label: "Anime.js", slug: "animedotjs" },
      { label: "PixiJS", slug: "pixi" },
      { label: "D3.js", slug: "d3" },
      { label: "Chart.js", slug: "chartdotjs" },
      { label: "ECharts", slug: "apacheecharts" },
      { label: "Recharts", slug: "recharts" },
      { label: "A-Frame", slug: "aframe" },
      { label: "React Three Fiber", slug: "react" },
      { label: "Three Fiber", slug: "threedotjs" },
      { label: "Cannon.js", slug: "javascript" },
      { label: "Rapier.js", slug: "rust" },
      { label: "Matter.js", slug: "matterdotjs" },
      { label: "Phaser.js", slug: "javascript" },
      { label: "Babylon.js", slug: "babylondotjs" },
      { label: "WebGPU", slug: "webgpu" },
      { label: "WebGL", slug: "webgl" },
      { label: "WebGL2", slug: "webgl" },
      { label: "OpenGL", slug: "opengl" },
      { label: "Vulkan", slug: "vulkan" },
      { label: "CUDA", slug: "nvidia" },
      { label: "OpenCL", slug: "opencl" },
      { label: "PhysX", slug: "nvidia" },
    ],
  },
  {
    group: "Frontend — State Management / Data",
    skills: [
      { label: "Redux", slug: "redux" },
      { label: "Zustand", slug: "zustand" },
      { label: "Recoil", slug: "recoil" },
      { label: "Jotai", slug: "jotai" },
      { label: "MobX", slug: "mobx" },
      { label: "Vuex", slug: "vue" },
      { label: "Pinia", slug: "pinia" },
      { label: "TanStack Query", slug: "tanstack" },
      { label: "React Query", slug: "tanstack" },
      { label: "SWR", slug: "vercel" },
      { label: "Zustand Persist", slug: "zustand" },
      { label: "Zustand Middleware", slug: "zustand" },
      { label: "Recoil Persist", slug: "recoil" },
      { label: "React Hook Form", slug: "react" },
      { label: "Formik", slug: "formik" },
      { label: "Yup", slug: "yup" },
      { label: "Zod", slug: "zod" },
      { label: "Immer", slug: "immer" },
      { label: "Luxon", slug: "luxon" },
      { label: "Day.js", slug: "dayjs" },
      { label: "Moment.js", slug: "moment" },
      { label: "date-fns", slug: "datefns" },
      { label: "Lodash", slug: "lodash" },
      { label: "Ramda", slug: "ramda" },
      { label: "RxJS", slug: "reactivex" },
      { label: "MobX-State-Tree", slug: "mobx" },
      { label: "Effector", slug: "effector" },
    ],
  },
  {
    group: "Frontend — Testing",
    skills: [
      { label: "Jest", slug: "jest" },
      { label: "Vitest", slug: "vitest" },
      { label: "React Testing Library", slug: "testinglibrary" },
      { label: "Cypress", slug: "cypress" },
      { label: "Playwright", slug: "playwright" },
      { label: "Testing Library", slug: "testinglibrary" },
      { label: "Mocha", slug: "mocha" },
      { label: "Chai", slug: "chai" },
      { label: "Storybook", slug: "storybook" },
    ],
  },
  {
    group: "Backend — Languages / Runtime",
    skills: [
      { label: "Node.js", slug: "nodedotjs" },
      { label: "Deno", slug: "deno" },
      { label: "Bun", slug: "bun" },
      { label: "Python", slug: "python" },
      { label: "Go", slug: "go" },
      { label: "Rust", slug: "rust" },
      { label: "Java", slug: "openjdk" },
      { label: "C#", slug: "csharp" },
      { label: "PHP", slug: "php" },
      { label: "Ruby", slug: "ruby" },
      { label: "Elixir", slug: "elixir" },
      { label: "Kotlin", slug: "kotlin" },
      { label: "Swift", slug: "swift" },
    ],
  },
  {
    group: "Backend — Frameworks / APIs",
    skills: [
      { label: "Express.js", slug: "express" },
      { label: "NestJS", slug: "nestjs" },
      { label: "Fastify", slug: "fastify" },
      { label: "Koa", slug: "koa" },
      { label: "Hono", slug: "hono" },
      { label: "Django", slug: "django" },
      { label: "Flask", slug: "flask" },
      { label: "FastAPI", slug: "fastapi" },
      { label: "Spring Boot", slug: "spring" },
      { label: ".NET Core", slug: "dotnet" },
      { label: "Fiber", slug: "go" },
      { label: "Fiber (Go)", slug: "go" },
      { label: "Gin (Go)", slug: "gin" },
      { label: "Ruby on Rails", slug: "rubyonrails" },
      { label: "Laravel", slug: "laravel" },
      { label: "AdonisJS", slug: "adonisjs" },
      { label: "Actix (Rust)", slug: "actix" },
      { label: "Rocket (Rust)", slug: "rocket" },
      { label: "Phoenix (Elixir)", slug: "phoenixframework" },
      { label: "Sinatra", slug: "rubysinatra" },
    ],
  },
  {
    group: "Backend — GraphQL / API",
    skills: [
      { label: "Apollo Server", slug: "apollographql" },
      { label: "GraphQL Yoga", slug: "graphql" },
      { label: "Hasura", slug: "hasura" },
      { label: "tRPC", slug: "trpc" },
      { label: "PostGraphile", slug: "postgraphile" },
      { label: "GraphQL", slug: "graphql" },
      { label: "REST API", slug: "swagger" },
      { label: "GraphQL Subscriptions", slug: "graphql" },
      { label: "PostgREST", slug: "postgresql" },
      { label: "Hasura Actions", slug: "hasura" },
      { label: "gRPC", slug: "grpc" },
      { label: "WebSockets", slug: "socketdotio" },
      { label: "WebRTC", slug: "webrtc" },
      { label: "HTTP/2", slug: "httpie" },
      { label: "HTTP/3", slug: "cloudflare" },
    ],
  },
  {
    group: "Backend — Auth / Security",
    skills: [
      { label: "JWT", slug: "jsonwebtokens" },
      { label: "OAuth2", slug: "oauth" },
      { label: "NextAuth.js", slug: "nextauth" },
      { label: "Auth0", slug: "auth0" },
      { label: "Passport.js", slug: "passport" },
      { label: "Firebase Auth", slug: "firebase" },
      { label: "Clerk", slug: "clerk" },
      { label: "Supabase Auth", slug: "supabase" },
      { label: "OAuth2 PKCE", slug: "oauth" },
      { label: "JWT Refresh Tokens", slug: "jsonwebtokens" },
      { label: "OpenID Connect", slug: "openid" },
    ],
  },
  {
    group: "Backend — Realtime / Messaging",
    skills: [
      { label: "Socket.io", slug: "socketdotio" },
      { label: "Pusher", slug: "pusher" },
      { label: "Firebase Realtime Database", slug: "firebase" },
      { label: "Supabase Realtime", slug: "supabase" },
      { label: "Redis Pub/Sub", slug: "redis" },
      { label: "Redis Streams", slug: "redis" },
      { label: "Apache Kafka", slug: "apachekafka" },
      { label: "Kafka", slug: "apachekafka" },
      { label: "RabbitMQ", slug: "rabbitmq" },
      { label: "Apache Pulsar", slug: "apachepulsar" },
      { label: "NATS", slug: "natsdotio" },
    ],
  },
  {
    group: "Backend — AI / ML",
    skills: [
      { label: "TensorFlow.js", slug: "tensorflow" },
      { label: "PyTorch", slug: "pytorch" },
      { label: "ONNX", slug: "onnx" },
      { label: "Hugging Face Transformers", slug: "huggingface" },
      { label: "LangChain", slug: "langchain" },
    ],
  },
  {
    group: "Backend — ORM / Prisma",
    skills: [
      { label: "Prisma", slug: "prisma" },
      { label: "Prisma ORM", slug: "prisma" },
      { label: "Drizzle", slug: "drizzle" },
      { label: "Drizzle ORM", slug: "drizzle" },
      { label: "TypeORM", slug: "typeorm" },
      { label: "Sequelize", slug: "sequelize" },
      { label: "Knex.js", slug: "knexdotjs" },
      { label: "MikroORM", slug: "typeorm" },
      { label: "Objection.js", slug: "knexdotjs" },
    ],
  },
  {
    group: "Database — SQL / Relational",
    skills: [
      { label: "PostgreSQL", slug: "postgresql" },
      { label: "MySQL", slug: "mysql" },
      { label: "MariaDB", slug: "mariadb" },
      { label: "SQLite", slug: "sqlite" },
      { label: "SQL Server", slug: "microsoftsqlserver" },
      { label: "CockroachDB", slug: "cockroachlabs" },
      { label: "Oracle Database", slug: "oracle" },
      { label: "PlanetScale", slug: "planetscale" },
    ],
  },
  {
    group: "Database — NoSQL / Document",
    skills: [
      { label: "MongoDB", slug: "mongodb" },
      { label: "DynamoDB", slug: "amazondynamodb" },
      { label: "Firebase Firestore", slug: "firebase" },
      { label: "CouchDB", slug: "apachecouchdb" },
      { label: "Redis", slug: "redis" },
      { label: "FaunaDB", slug: "fauna" },
      { label: "Apache Cassandra", slug: "apachecassandra" },
      { label: "Supabase", slug: "supabase" },
    ],
  },
  {
    group: "Database — Search / Analytics",
    skills: [
      { label: "Elasticsearch", slug: "elasticsearch" },
      { label: "Apache Solr", slug: "apachesolr" },
      { label: "Meilisearch", slug: "meilisearch" },
      { label: "Algolia", slug: "algolia" },
    ],
  },
  {
    group: "Database — Graph / Time-series",
    skills: [
      { label: "Neo4j", slug: "neo4j" },
      { label: "ArangoDB", slug: "arangodb" },
      { label: "Dgraph", slug: "dgraph" },
      { label: "InfluxDB", slug: "influxdb" },
      { label: "TimescaleDB", slug: "timescale" },
      { label: "ClickHouse", slug: "clickhouse" },
      { label: "Apache Druid", slug: "apachedruid" },
    ],
  },
  {
    group: "Cloud / DevOps — Containers",
    skills: [
      { label: "Docker", slug: "docker" },
      { label: "Podman", slug: "podman" },
      { label: "Kubernetes", slug: "kubernetes" },
      { label: "Docker Compose", slug: "docker" },
      { label: "Vagrant", slug: "vagrant" },
      { label: "Helm", slug: "helm" },
      { label: "Argo CD", slug: "argo" },
      { label: "NixOS", slug: "nixos" },
    ],
  },
  {
    group: "Cloud / DevOps — IaC / Config",
    skills: [
      { label: "Terraform", slug: "terraform" },
      { label: "Pulumi", slug: "pulumi" },
      { label: "Ansible", slug: "ansible" },
      { label: "Chef", slug: "chef" },
      { label: "Puppet", slug: "puppet" },
    ],
  },
  {
    group: "Cloud / DevOps — Providers",
    skills: [
      { label: "AWS", slug: "amazonaws" },
      { label: "Azure", slug: "microsoftazure" },
      { label: "Google Cloud", slug: "googlecloud" },
      { label: "Cloudflare", slug: "cloudflare" },
      { label: "DigitalOcean", slug: "digitalocean" },
      { label: "Render", slug: "render" },
      { label: "Railway", slug: "railway" },
      { label: "Fly.io", slug: "flydotio" },
      { label: "Vercel", slug: "vercel" },
      { label: "Netlify", slug: "netlify" },
      { label: "Supabase", slug: "supabase" },
      { label: "Firebase", slug: "firebase" },
      { label: "Replit", slug: "replit" },
      { label: "Glitch", slug: "glitch" },
      { label: "OVH", slug: "ovh" },
      { label: "Scaleway", slug: "scaleway" },
      { label: "Cloudflare Pages", slug: "cloudflarepages" },
      { label: "Cloudflare Workers", slug: "cloudflareworkers" },
      { label: "Firebase Functions", slug: "firebase" },
      { label: "Edge Functions", slug: "vercel" },
    ],
  },
  {
    group: "Cloud / DevOps — Storage / CDN",
    skills: [
      { label: "Cloudflare R2", slug: "cloudflare" },
      { label: "AWS S3", slug: "amazons3" },
      { label: "Google Cloud Storage", slug: "googlecloudstorage" },
      { label: "Supabase Storage", slug: "supabase" },
      { label: "Firebase Storage", slug: "firebase" },
      { label: "Cloudinary", slug: "cloudinary" },
      { label: "Imgix", slug: "imgix" },
    ],
  },
  {
    group: "Cloud / DevOps — CI/CD",
    skills: [
      { label: "GitHub Actions", slug: "githubactions" },
      { label: "GitLab CI/CD", slug: "gitlab" },
      { label: "Jenkins", slug: "jenkins" },
      { label: "CircleCI", slug: "circleci" },
      { label: "Vercel", slug: "vercel" },
      { label: "Netlify", slug: "netlify" },
      { label: "Turborepo", slug: "turborepo" },
      { label: "AppVeyor", slug: "appveyor" },
      { label: "Travis CI", slug: "travisci" },
    ],
  },
  {
    group: "Cloud / DevOps — Monitoring / Logging",
    skills: [
      { label: "Sentry", slug: "sentry" },
      { label: "LogRocket", slug: "logrocket" },
      { label: "Datadog", slug: "datadog" },
      { label: "Datadog RUM", slug: "datadog" },
      { label: "Grafana", slug: "grafana" },
      { label: "Prometheus", slug: "prometheus" },
      { label: "Google Analytics", slug: "googleanalytics" },
      { label: "Plausible", slug: "plausibleanalytics" },
      { label: "Mixpanel", slug: "mixpanel" },
      { label: "Apache Superset", slug: "apachesuperset" },
      { label: "Kibana", slug: "kibana" },
      { label: "Logstash", slug: "logstash" },
      { label: "OpenTelemetry", slug: "opentelemetry" },
      { label: "Firebase Crashlytics", slug: "firebase" },
      { label: "Amplitude", slug: "amplitude" },
      { label: "Segment", slug: "segment" },
    ],
  },
  {
    group: "Productivity — Version Control",
    skills: [
      { label: "Git", slug: "git" },
      { label: "GitHub", slug: "github" },
      { label: "GitLab", slug: "gitlab" },
      { label: "Bitbucket", slug: "bitbucket" },
      { label: "npm", slug: "npm" },
      { label: "pnpm", slug: "pnpm" },
      { label: "Yarn", slug: "yarn" },
    ],
  },
  {
    group: "Productivity — Code Quality",
    skills: [
      { label: "ESLint", slug: "eslint" },
      { label: "Prettier", slug: "prettier" },
      { label: "Stylelint", slug: "stylelint" },
      { label: "SonarQube", slug: "sonarqube" },
      { label: "Biome", slug: "biome" },
    ],
  },
  {
    group: "Productivity — API Testing",
    skills: [
      { label: "Postman", slug: "postman" },
      { label: "Insomnia", slug: "insomnia" },
      { label: "Swagger", slug: "swagger" },
      { label: "Redoc", slug: "redoc" },
      { label: "Apifox", slug: "apifox" },
    ],
  },
  {
    group: "Productivity — Project Management",
    skills: [
      { label: "Jira", slug: "jira" },
      { label: "Trello", slug: "trello" },
      { label: "Notion", slug: "notion" },
      { label: "Linear", slug: "linear" },
      { label: "Asana", slug: "asana" },
      { label: "Monday.com", slug: "monday" },
      { label: "ClickUp", slug: "clickup" },
    ],
  },
  {
    group: "Productivity — Design / Prototyping",
    skills: [
      { label: "Figma", slug: "figma" },
      { label: "Sketch", slug: "sketch" },
      { label: "Adobe XD", slug: "adobexd" },
      { label: "Canva", slug: "canva" },
    ],
  },
  {
    group: "Productivity — Icons / Fonts",
    skills: [
      { label: "Heroicons", slug: "tailwindcss" },
      { label: "Radix Icons", slug: "radixui" },
      { label: "Remix Icons", slug: "remix" },
      { label: "Iconify", slug: "iconify" },
      { label: "Font Awesome", slug: "fontawesome" },
      { label: "Simple Icons", slug: "simpleicons" },
      { label: "Material Icons", slug: "mui" },
      { label: "Google Fonts", slug: "googlefonts" },
      { label: "Inter", slug: "googlefonts" },
      { label: "Poppins", slug: "googlefonts" },
      { label: "Space Grotesk", slug: "googlefonts" },
      { label: "Fira Code", slug: "mozilla" },
      { label: "JetBrains Mono", slug: "jetbrains" },
    ],
  },
  {
    group: "Productivity — Editors / Rich Text",
    skills: [
      { label: "Monaco Editor", slug: "microsoft" },
      { label: "CodeMirror", slug: "codemirror" },
      { label: "Quill.js", slug: "quill" },
      { label: "Slate.js", slug: "slate" },
      { label: "TinyMCE", slug: "tinymce" },
      { label: "CKEditor", slug: "ckeditor" },
    ],
  },
  {
    group: "Productivity — Markdown / MDX",
    skills: [
      { label: "Markdown-it", slug: "markdown" },
      { label: "Remark", slug: "remark" },
      { label: "Rehype", slug: "rehype" },
      { label: "MDX", slug: "mdx" },
      { label: "React Markdown", slug: "react" },
      { label: "Next MDX", slug: "nextdotjs" },
    ],
  },
  {
    group: "Productivity — Headless CMS",
    skills: [
      { label: "Sanity.io", slug: "sanity" },
      { label: "Strapi", slug: "strapi" },
      { label: "Contentful", slug: "contentful" },
      { label: "Prismic", slug: "prismic" },
      { label: "Ghost", slug: "ghost" },
      { label: "Netlify CMS", slug: "netlify" },
      { label: "Storyblok", slug: "storyblok" },
      { label: "Directus", slug: "directus" },
      { label: "Notion API", slug: "notion" },
      { label: "Supabase API", slug: "supabase" },
    ],
  },
  {
    group: "Desktop / Mobile — Cross-platform",
    skills: [
      { label: "Electron", slug: "electron" },
      { label: "Tauri", slug: "tauri" },
      { label: "Capacitor", slug: "capacitor" },
      { label: "React Native", slug: "react" },
      { label: "Flutter", slug: "flutter" },
    ],
  },
  {
    group: "Desktop / Mobile — Web Servers",
    skills: [
      { label: "NGINX", slug: "nginx" },
      { label: "Apache", slug: "apache" },
      { label: "Caddy", slug: "caddy" },
    ],
  },
];

/** Flat list of all skills for quick lookup */
export const ALL_SKILLS = SKILLS_CATALOG.flatMap((g) => g.skills);

/** Map label -> slug for Skills component */
export const SKILL_LABEL_TO_SLUG: Record<string, string> = Object.fromEntries(
  ALL_SKILLS.map((s) => [s.label, s.slug])
);
